### ISSUE TITLE
makeString function not working properly

### ISSUE THREAD

**Issue by alexgarciab** [stape-io/pinterest-tag#10]
I am testing this Tag and I am getting the following error message from the Pinterest API:

`{"code":1,"message":"Invalid request: 50 is not of type string, 50 is not of type string"}`

I see in the code you have a "makeString" function to convert from number (int / double) to string these values: "value" and "item_price".

But for some reason it is not working. It is still sending the values as numbers and not strings. My input is a double number (e.g. 50.00). The template should convert it to string to be able to send it properly to the API.

![new](https://github.com/stape-io/pinterest-tag/assets/6924386/07d38c41-91e0-4534-a31a-56c056d58e9f)

**Comment by Bukashk0zzz** [comment]
Issue fixed
